window.LEVEL_UP_LESSONS = [
  {
    id: 2, title: "FRIENDS: SAME OR DIFFERENT?", theme: "friendship · teamwork · comparison", accent: "pink",
    objective: "Compare people fairly and build a strong project team.", grammar: "comparatives · superlatives · as…as", pronunciation: "sentence stress in comparisons",
    context: "Maya and Leo have been paired for a media project. Maya plans everything; Leo works fast at the last minute. Can their differences become a strength?",
    input: "Maya is more organised than Leo, but Leo is a bit more spontaneous. They are both creative, and Maya is just as curious as Leo. Maya is the most reliable planner in the group; Leo is the fastest editor. They do not need to be the same to work well together.",
    words: [["reliable","you can trust this person"],["supportive","ready to help and encourage"],["easy-going","relaxed and not easily worried"],["have something in common","share an interest or quality"],["count on","depend on someone"]],
    sortTitle: "STRENGTH OR WORKING STYLE?", categories: ["strength","style"], sort: [["reliable","strength"],["supportive","strength"],["plans every detail","style"],["works at the last minute","style"]],
    notice: ["Maya is more organised than Leo.","Maya is just as curious as Leo.","Leo is the fastest editor."],
    rule: "Сравнительная степень показывает различие: faster / more organised. as…as — равенство. Превосходная степень выделяет одного из группы: the fastest.", mistake: "more kinder ✗ → kinder ✓",
    type: [["Leo is ___ (spontaneous) than Maya.","more spontaneous","Use more + a longer adjective."],["They are ___ creative ___ each other.","as creative as","Use as + adjective + as."]],
    speaking: "Choose the best two-person team for a school project. Compare their strengths and defend your choice.", useful: ["…is more…than…","They are both…","…is as…as…","The best choice is…because…"],
    oge: {kind:"READING MATCH", task:"A student loves taking photos but needs a reliable partner who always meets deadlines. Who is the better partner?", options:["Maya","Leo","Either — no evidence"], answer:0, tip:"Ищите совпадение по смыслу: taking photos = creative interest; meets deadlines = reliable and organised."},
    writing: "Write a 60–70-word recommendation for how Maya and Leo should divide the project roles.", home:["Review five friendship chunks.","Write four true comparisons.","Describe a good teammate in 60 words."]
  },
  {
    id: 3, title: "THE DAY EVERYTHING WENT WRONG", theme: "stories · accidents · timelines", accent: "yellow",
    objective: "Tell a clear story with events and background actions.", grammar: "Past Simple · Past Continuous · when/while", pronunciation: "-ed endings /t/ /d/ /ɪd/",
    context: "Noah was travelling across town to film a skate event. His phone battery was at 4%. Then the problems started.",
    input: "Noah was waiting for the bus when he realised his camera was still at home. While he was running back, it started to rain. He grabbed the camera, but he missed the next bus. In the end, a neighbour drove him to the event — and Noah arrived just before the final round.",
    words: [["miss the bus","arrive too late for it"],["run out of battery","have no power left"],["take the wrong turn","go in the wrong direction"],["realise","suddenly understand"],["in the end","finally, after everything"]],
    sortTitle:"EVENT OR BACKGROUND?", categories:["event","background"], sort:[["realised","event"],["started","event"],["was waiting","background"],["was running","background"]],
    notice:["He was waiting when he realised…","While he was running, it started to rain.","A neighbour drove him."],
    rule:"Past Continuous показывает фон или действие в процессе; Past Simple — завершённое событие. when часто вводит событие, while — параллельный фон.", mistake:"When I was arrived ✗ → When I arrived ✓",
    type:[["Noah ___ (wait) when he realised the problem.","was waiting","The longer background action was in progress."],["While he was running, it ___ (start) to rain.","started","Use Past Simple for the event that happened." ]],
    speaking:"Reconstruct the disaster day. Then tell it from the neighbour’s point of view.", useful:["At first…","While I was…","Suddenly…","Luckily…","In the end…"],
    oge:{kind:"GRAMMAR",task:"While Noah ___ (RUN) home, it started to rain.",options:["ran","was running","has run"],answer:1,tip:"Сначала определите: это фон в процессе или завершённое событие? Здесь действие уже продолжалось."},
    writing:"Write a 70–90-word ending: What happened after Noah arrived?", home:["Sort ten -ed verbs by sound.","Complete a short story gap task.","Record a one-minute true mini-story."]
  },
  {
    id:4,title:"CAN YOU LIVE WITHOUT YOUR PHONE?",theme:"phones · habits · balance",accent:"blue",objective:"Quantify digital habits and negotiate realistic phone rules.",grammar:"countable/uncountable · quantifiers",pronunciation:"weak forms in a lot of / a few",
    context:"The group tries a six-hour phone-free challenge. Everyone expects it to be easy. It isn’t.",input:"Leo received a lot of notifications before the challenge. He had too many group chats and very little quiet time. Maya took a few photos but did not post them. Noah had enough time to finish a video. Zara said six hours was not much time — but she still checked her empty pocket eleven times.",
    words:[["screen time","time spent using a screen"],["notification","an alert from an app"],["scroll","move through content"],["cut down on","reduce an amount"],["feel left out","feel excluded"]],sortTitle:"COUNTABLE OR UNCOUNTABLE?",categories:["countable","uncountable"],sort:[["notifications","countable"],["messages","countable"],["time","uncountable"],["information","uncountable"]],notice:["too many group chats","very little quiet time","enough time"],rule:"many/few — с исчисляемыми во множественном числе; much/little — с неисчисляемыми. a lot of подходит к обоим типам.",mistake:"many information ✗ → much information ✓",
    type:[["I get too ___ notifications.","many","Notifications are countable."],["I don’t have ___ time offline.","enough","The meaning is ‘not sufficient’." ]],speaking:"Audit your phone habits and agree on three realistic rules for homework, meals and bedtime.",useful:["I spend a lot of time…","I get too many…","I don’t have enough…","We could cut down on…"],oge:{kind:"LISTENING DETAIL",task:"Which person completed a creative task during the challenge?",options:["Leo","Noah","Zara"],answer:1,tip:"Не выбирайте по одному знакомому слову. Найдите действие, которое соответствует completed a creative task."},writing:"Write a short challenge comment: one result and one practical tip.",home:["Keep a one-day screen-time log.","Complete a quantifier challenge.","Write a five-sentence reflection."]
  },
  {
    id:5,title:"WHAT SHOULD I DO?",theme:"teen problems · advice · boundaries",accent:"pink",objective:"Give tactful advice and distinguish advice from rules.",grammar:"should · must · have to",pronunciation:"should /ʃəd/ · have to /ˈhæftə/",
    context:"Four anonymous problem cards arrive: group-chat pressure, no sleep, a friendship conflict and too much homework.",input:"One student is exhausted because messages arrive all night. Another has to finish a group task alone. Zara says they should ask questions before giving advice. Maya adds: ‘You mustn’t share private messages, but you don’t have to answer immediately.’",
    words:[["exhausted","extremely tired"],["deal with","take action about a problem"],["set a boundary","say clearly what is acceptable"],["talk it through","discuss until it is clearer"],["take a break","stop for a short rest"]],sortTitle:"HOW STRONG IS IT?",categories:["advice","obligation"],sort:[["should take a break","advice"],["could talk it through","advice"],["have to follow the rule","obligation"],["mustn’t share it","obligation"]],notice:["You should ask first.","You mustn’t share private messages.","You don’t have to answer immediately."],rule:"should — совет; have to/must — необходимость; mustn’t — запрет; don’t have to — отсутствующая необходимость.",mistake:"You mustn’t reply = тебе нельзя отвечать. You don’t have to reply = тебе не обязательно отвечать.",type:[["You ___ share private messages.","mustn't","This is a prohibition."],["Maybe you ___ take a break.","should","This is advice, not a rule."]],speaking:"Run an advice clinic. Ask two follow-up questions before suggesting a three-step solution.",useful:["What exactly happened?","Maybe you could…","It might help to…","You don’t have to…"],oge:{kind:"WORD FORM",task:"The student felt completely ___ after sleeping for only three hours. (EXHAUST)",options:["exhaust","exhausted","exhaustion"],answer:1,tip:"Определите часть речи до выбора формы: после felt нужно прилагательное, описывающее состояние человека."},writing:"Write a 60–80-word supportive reply: empathy + advice + reason.",home:["Sort modal meanings.","Rewrite three blunt replies tactfully.","Prepare one anonymous teen problem."]
  },
  {
    id:6,title:"CHECKPOINT 1: THE SCHOOL SURVIVAL GUIDE",theme:"checkpoint · school · practical English",accent:"yellow",objective:"Create a useful guide for a new student.",grammar:"Episodes 1–5 review · basic linkers",pronunciation:"sentence stress + endings",
    context:"A new student is joining in the middle of term. The group has one page to explain what really helps.",input:"The new student enjoys creative projects, worries about speaking in class and checks every instruction twice. They are moving this week, so routines are changing. Your guide must include people, places, rules and one honest story.",words:[["settle in","become comfortable in a new place"],["ask for help","request support"],["get involved","start taking part"],["keep up with","stay at the same level or pace"],["make a mistake","do something incorrectly"]],sortTitle:"GUIDE SECTION",categories:["do","dont"],sort:[["ask follow-up questions","do"],["join one activity","do"],["pretend you understand","dont"],["compare yourself with everyone","dont"]],notice:["First, find one person you can count on.","You don’t have to understand everything on day one.","In the end, mistakes help you learn."],rule:"Checkpoint: выбирайте форму по смыслу и соединяйте идеи через first, also, but, because, so, in the end.",mistake:"Нельзя соединять каждое предложение только через and. Выбирайте связь: причина, контраст, результат.",type:[["A new student ___ ask for help.","should","Give useful advice."],["This week, they ___ (move) house.","are moving","It is a temporary current situation."]],speaking:"Deliver a 90-second New Student Survival Guide with three rules, two tips and one personal story.",useful:["First…","You should…","You don’t have to…","For example…","In the end…"],oge:{kind:"MIXED CHECKPOINT",task:"Which opening answers a survey question directly and adds detail?",options:["School clubs.","I prefer school clubs because they help me meet people.","There are many clubs."],answer:1,tip:"Формула устного опроса: прямой ответ + одна релевантная деталь."},writing:"Add a 70–90-word section to the survival guide.",home:["Complete the self-assessment.","Revise five insecure words.","Polish your guide paragraph."]
  },
  {
    id:7,title:"HAVE YOU EVER TRIED IT?",theme:"experiences · challenge · follow-up",accent:"blue",objective:"Discuss life experience and ask natural follow-up questions.",grammar:"Present Perfect · Past Simple",pronunciation:"I’ve / haven’t · weak have",
    context:"The group must choose one unusual weekend experience to feature.",input:"Zara has tried indoor climbing twice. She first tried it last winter and loved it. Leo has never been paddleboarding, but he has already booked a beginner lesson. Noah went to an escape room in May; he did not escape, but the experience was still worth it.",words:[["take part in","participate"],["manage to","succeed in doing"],["give up","stop trying"],["worth it","good enough to justify the effort"],["memorable","easy to remember"]],sortTitle:"EXPERIENCE OR FINISHED TIME?",categories:["experience","finished"],sort:[["has tried twice","experience"],["has never been","experience"],["tried last winter","finished"],["went in May","finished"]],notice:["Have you ever tried it?","I’ve tried it twice.","I first tried it last winter."],rule:"Present Perfect — жизненный опыт без законченного времени. Past Simple — конкретное завершённое время: last winter, in May.",mistake:"I have tried it last year ✗ → I tried it last year ✓",type:[["___ you ever ___ (try) climbing?","have you ever tried","Use have + subject + ever + V3."],["I ___ (try) it last summer.","tried","A finished time requires Past Simple."]],speaking:"Interview your tutor about experiences, ask follow-up questions and pitch the best activity.",useful:["Have you ever…?","Yeah, once.","When did you…?","What was it like?","It was worth it because…"],oge:{kind:"INTERVIEW",task:"Which is the strongest answer to ‘Have you ever tried an unusual sport?’",options:["Yes.","Yes, I have. I tried paddleboarding last summer and really enjoyed it.","I like sport."],answer:1,tip:"Дайте полный прямой ответ, затем одну конкретную деталь в Past Simple."},writing:"Write a short experience recommendation with a rating and reason.",home:["Review ten participles.","Write six experience questions.","Rehearse a 60-second answer."]
  },
  {
    id:8,title:"WORTH THE MONEY?",theme:"money · shopping · value",accent:"pink",objective:"Compare offers and make a reasoned spending decision.",grammar:"too · enough · comparatives",pronunciation:"prices + word stress",
    context:"The team has £60 for one shared purchase. Every advert says ‘best deal’.",input:"The first headphones are cheap but not strong enough for daily use. The second pair is more expensive, but the price includes a two-year guarantee. A monthly subscription looks cheaper, but it becomes the most expensive option after eight months.",words:[["afford","have enough money for"],["save up","keep money for later"],["waste","use badly"],["discount","a reduction in price"],["good value","good quality for the price"]],sortTitle:"FACT OR OPINION?",categories:["fact","opinion"],sort:[["costs £45","fact"],["includes a guarantee","fact"],["looks amazing","opinion"],["the best deal ever","opinion"]],notice:["not strong enough","too expensive","the most expensive option"],rule:"too + adjective = чрезмерно; adjective + enough = достаточно. enough ставится после прилагательного, но перед существительным: enough money.",mistake:"enough cheap ✗ → cheap enough ✓",type:[["The cheap pair isn’t strong ___.","enough","Enough comes after the adjective."],["The subscription is ___ expensive after eight months.","too","Use too before an adjective."]],speaking:"Negotiate a £60 budget and defend the best-value option.",useful:["We can afford…","It’s cheaper than…","It isn’t…enough.","It’s good value because…"],oge:{kind:"PRACTICAL READING",task:"You need headphones for two years and cannot spend more than £60. Which key detail matters most?",options:["colour","guarantee","advert slogan"],answer:1,tip:"Сначала выделите ограничения пользователя; затем ищите точное условие, которое им соответствует."},writing:"Write a 60–80-word message comparing two options and recommending one.",home:["Review money collocations.","Build a mini-budget.","Complete one advert-reading task."]
  },
  {
    id:9,title:"WHAT ARE WE DOING THIS WEEKEND?",theme:"plans · arrangements · prediction",accent:"yellow",objective:"Make and revise a shared weekend plan.",grammar:"will · going to · Present Continuous",pronunciation:"we’ll · going to",
    context:"Four schedules, one weekend and tickets that may sell out.",input:"Maya is meeting her cousin on Saturday morning. Leo is going to buy the tickets tonight because the group has already decided. Zara thinks the outdoor film will probably sell out. Noah has just seen dark clouds and says, ‘It’ll rain — let’s book the indoor event instead.’",
    words:[["be available","have free time"],["book","reserve a place"],["sold out","with no tickets left"],["meet up","meet socially"],["backup plan","alternative plan"]],sortTitle:"WHAT KIND OF FUTURE?",categories:["plan","prediction"],sort:[["is meeting at ten","plan"],["is going to buy tickets","plan"],["will probably sell out","prediction"],["it’ll rain","prediction"]],notice:["I’m meeting her at ten.","I’m going to buy the tickets.","It’ll probably sell out."],rule:"Present Continuous — договорённость; going to — намерение/план; will — прогноз или решение в момент речи. Выбор зависит от смысла.",mistake:"Не выбирайте будущее время только по русскому переводу ‘буду’. Сначала определите функцию.",type:[["We ___ (meet) at six; it’s in the calendar.","are meeting","A fixed arrangement uses Present Continuous."],["I think it ___ be crowded.","will","This is a prediction."]],speaking:"Use the schedule clues to negotiate Plan A and Plan B.",useful:["Are you up for…?","I’m meeting…","We’re going to…","It’ll probably…","Sounds good to me."],oge:{kind:"LISTENING MATCH",task:"Which phrase signals the final decision rather than the first idea?",options:["At first…","Actually, let’s…","Maybe…"],answer:1,tip:"В аудировании отслеживайте поворот после but, actually, so — там часто звучит окончательное решение."},writing:"Send the final group message with time, place and backup plan.",home:["Choose future forms in eight contexts.","Complete your weekend calendar.","Write an invitation and reply."]
  },
  {
    id:10,title:"FOOD THAT MAKES SENSE",theme:"food · requirements · choices",accent:"blue",objective:"Design a practical event menu for different needs.",grammar:"quantifiers · relative clauses",pronunciation:"food word stress + linking",
    context:"The school event needs affordable snacks. One guest has a nut allergy; another does not eat meat.",input:"We need dishes that are easy to serve and food which does not contain nuts. Zara knows a café where the wraps are fresh and filling. Leo suggests mini burgers, but there are not enough vegetarian portions. The final menu must be safe, affordable and not too complicated.",words:[["ingredient","food used to make a dish"],["filling","making you feel full"],["contain","have something inside"],["avoid","stay away from"],["portion","an amount served to one person"]],sortTitle:"SAFE OR NEEDS CHECKING?",categories:["safe","check"],sort:[["labelled nut-free","safe"],["sealed fruit cup","safe"],["unlabelled sauce","check"],["homemade cake with no list","check"]],notice:["dishes that are easy to serve","a café where the wraps are fresh","food which does not contain nuts"],rule:"who — люди; which/that — предметы; where — места. Определительное придаточное уточняет, о ком или о чём речь.",mistake:"a café which we eat there ✗ → a café where we eat ✓",type:[["We need food ___ is easy to serve.","that","Use that/which for things."],["This is the café ___ they make fresh wraps.","where","Use where for a place."]],speaking:"Build a menu that meets budget, preference and allergy constraints.",useful:["We need a dish that…","This is suitable for…","It contains…","There aren’t enough…"],oge:{kind:"GRAMMAR IN CONTEXT",task:"Choose the correct word: ‘The café ___ we ordered the wraps is nearby.’",options:["who","where","which people"],answer:1,tip:"Определите, что заменяет слово: человека, предмет или место."},writing:"Write a 70-word menu description or mini-review with two relative clauses.",home:["Retrieve food vocabulary.","Join six sentence pairs.","Write one mini-review."]
  },
  {
    id:11,title:"GAME, FILM OR SERIES?",theme:"media · reviews · opinions",accent:"pink",objective:"Recommend media and respond to a different opinion.",grammar:"gerund · infinitive basics",pronunciation:"adjective stress + opinion intonation",
    context:"Everyone nominates one Friday title. No spoilers allowed.",input:"Maya enjoys watching character-driven series. Leo wants to choose a fast game and promises to avoid giving spoilers. Zara finished watching a mystery yesterday and recommends seeing it without reading reviews first. Noah would like to try something funny, not another dark story.",words:[["plot","the events in a story"],["setting","where and when a story happens"],["gripping","very exciting"],["predictable","easy to guess"],["overrated","praised more than deserved"]],sortTitle:"GERUND OR INFINITIVE?",categories:["ing","to"],sort:[["enjoy watching","ing"],["finish watching","ing"],["want to choose","to"],["decide to try","to"]],notice:["enjoys watching","wants to choose","finished watching"],rule:"После enjoy/finish обычно используем -ing; после want/decide/would like — to + verb. Запоминаем модель вместе с глаголом.",mistake:"I enjoy to watch ✗ → I enjoy watching ✓",type:[["I really enjoy ___ (watch) mysteries.","watching","Enjoy is followed by -ing."],["We decided ___ (try) the new game.","to try","Decide is followed by to + verb."]],speaking:"Give a 90-second spoiler-free pitch and respond politely to a different view.",useful:["It’s about…","What I liked most was…","It’s not really my thing.","I’d recommend it to…"],oge:{kind:"HEADING MATCH",task:"A paragraph focuses on why the ending is easy to guess. Which heading fits best?",options:["Great characters","Too predictable","A beautiful setting"],answer:1,tip:"Заголовок должен передавать главную мысль всего абзаца, а не отдельное знакомое слово."},writing:"Write an 80–100-word mini-review with two reasons and a recommendation.",home:["Review verb patterns.","Improve a weak review.","Prepare a 45-second recommendation."]
  },
  {
    id:12,title:"CHECKPOINT 2: PLAN THE PERFECT POP-UP",theme:"checkpoint · budget · event",accent:"yellow",objective:"Create and pitch a complete pop-up event.",grammar:"Episodes 7–11 review · planning linkers",pronunciation:"clear thought groups",
    context:"The group can run one event: gaming lounge, mini film festival, street-food lab or active challenge.",input:"The venue holds forty people and closes at 8 p.m. The budget is £180. Visitors have asked for an activity that is social, affordable and easy to join. One room has already been booked, so the plan needs a backup space.",words:[["venue","place for an event"],["allocate","give money/time to a purpose"],["constraint","limit or rule"],["proposal","a suggested plan"],["contingency","backup for a possible problem"]],sortTitle:"NEED OR NICE TO HAVE?",categories:["need","extra"],sort:[["safe venue","need"],["stay under budget","need"],["printed badges","extra"],["decorative lights","extra"]],notice:["First of all, we need…","However, the budget is limited.","As a result, we’ll…"],rule:"Checkpoint: соединяйте план через first of all, however, for example, as a result и выбирайте изученные формы по функции.",mistake:"however не соединяет два предложения одной запятой. Используйте точку/точку с запятой.",type:[["The room ___ already ___ (book).","has already been booked","The result matters now; passive form."],["If the first room is busy, we ___ use the hall.","will","Real future contingency: first conditional."]],speaking:"Deliver a two-minute pop-up proposal with budget, schedule and backup.",useful:["First of all…","The best value is…","However…","If…, we’ll…","As a result…"],oge:{kind:"CHECKPOINT",task:"Which plan meets all three constraints: social, under £180, easy for beginners?",options:["£220 expert tournament","£160 team quiz with beginner round","£175 solo film screening"],answer:1,tip:"Составьте мини-таблицу ограничений и исключайте вариант только после проверки каждого пункта."},writing:"Write an 80–100-word event confirmation message.",home:["Complete the self-assessment.","Revise one weak grammar family.","Finalise the confirmation message."]
  },
  {
    id:13,title:"IF THIS HAPPENS…",theme:"risk · weather · Plan B",accent:"blue",objective:"Predict realistic consequences and make contingency plans.",grammar:"first conditional",pronunciation:"pausing across if-clauses",
    context:"An outdoor filming day may be affected by rain, transport and low batteries.",input:"If it rains, the group will film inside the station café. If the bus is delayed, Maya will message the venue. Everyone will bring a power bank in case a phone runs out of battery. If they prepare for the obvious risks, one surprise will not ruin the day.",words:[["forecast","prediction of weather"],["delay","make something late"],["backup","alternative kept ready"],["equipment","tools needed for an activity"],["be prepared","be ready"]],sortTitle:"CONDITION OR RESULT?",categories:["condition","result"],sort:[["if it rains","condition"],["if the bus is delayed","condition"],["we will film inside","result"],["Maya will message","result"]],notice:["If it rains, we’ll film inside.","We’ll message you if the bus is delayed."],rule:"First conditional: if + Present Simple, will + verb. Порядок частей можно менять; запятая нужна, когда if-clause стоит первой.",mistake:"If it will rain ✗ → If it rains ✓",type:[["If it ___ (rain), we’ll film inside.","rains","Use Present Simple after if."],["We ___ (call) you if the bus is late.","will call","Use will in the result clause."]],speaking:"Build a plan that survives three surprise problem cards.",useful:["If this happens…","We’ll…","Our backup is…","just in case"],oge:{kind:"LISTENING DETAIL",task:"Before listening, what differences should you mark in the options?",options:["font and colour","time, place, reason and action","number of words only"],answer:1,tip:"До аудирования выделите смысловые различия в вариантах — это создаёт цель для слушания."},writing:"Write a concise Plan B message with three first-conditionals.",home:["Build a conditional chain.","Retrieve weather/equipment words.","Write a 60-word contingency message."]
  },
  {
    id:14,title:"IF YOU COULD CHANGE ONE THING…",theme:"school · ideas · imagination",accent:"pink",objective:"Discuss imagined changes and explain their impact.",grammar:"second conditional introduction",pronunciation:"I’d + contrastive stress",
    context:"The school invites one realistic idea and one bold dream idea.",input:"Maya says, ‘If we had a quiet studio, more students would record podcasts.’ Leo would create a flexible project day if he could change one rule. Zara supports both ideas, but she asks whether they would help everyone, not only the media club.",words:[["improve","make better"],["provide","make available"],["facility","place/equipment for a purpose"],["opportunity","chance to do something"],["feasible","possible and practical"]],sortTitle:"REAL PLAN OR IMAGINED CHANGE?",categories:["real","imagined"],sort:[["If it rains, we’ll move inside.","real"],["If the room is free, we’ll use it.","real"],["If we had a studio, we’d record more.","imagined"],["If I could change a rule, I’d…","imagined"]],notice:["If we had a studio, we would record more.","If I could change one rule, I’d…"],rule:"Second conditional: if + Past Simple, would + verb. Он описывает воображаемую или маловероятную ситуацию сейчас/в будущем.",mistake:"If I would have ✗ → If I had, I would… ✓",type:[["If we ___ (have) more space, we’d create a studio.","had","Use Past Simple in the if-clause."],["More students ___ join if it were free.","would","Use would + verb for the imagined result."]],speaking:"Pitch one realistic improvement and one bold hypothetical idea.",useful:["If we had…","More students would…","I see the point, but…","That could work if…"],oge:{kind:"MONOLOGUE PLAN",task:"Which structure gives a clear response?",options:["random ideas","problem → proposal → reason → example","memorised introduction only"],answer:1,tip:"Используйте пункты задания как маршрут и добавляйте причину/пример к каждому основному тезису."},writing:"Write an 80–100-word school improvement proposal.",home:["Contrast first/second conditional.","Edit a proposal.","Rehearse four monologue points."]
  },
  {
    id:15,title:"MADE, SHARED, REMIXED",theme:"AI · media · sources",accent:"yellow",objective:"Describe processes and make responsible sharing decisions.",grammar:"passive voice introduction",pronunciation:"weak is/was + content stress",
    context:"A viral image, an AI-generated poster and a fan edit appear in the project chat.",input:"The poster was generated with an AI tool and then edited by Maya. The original photo was taken at the school event. A false caption was added later by an unknown account. The image is not automatically fake because AI was used, but the source must be checked before it is shared.",words:[["generate","create using a system"],["source","where information comes from"],["credit","name the creator"],["permission","agreement allowing an action"],["misleading","creating a false impression"]],sortTitle:"SHARE OR CHECK FIRST?",categories:["share","check"],sort:[["official source + clear date","share"],["creator credited","share"],["unknown account","check"],["dramatic caption without evidence","check"]],notice:["was generated","was taken","is shared"],rule:"Passive: be + V3. Используем, когда важнее действие/результат, а исполнитель неизвестен или неважен.",mistake:"The image generated yesterday ✗ → The image was generated yesterday ✓",type:[["The poster ___ (generate) with an AI tool.","was generated","Past passive: was + V3."],["Images ___ (share) every minute.","are shared","Present passive with plural subject."]],speaking:"Give Share / Don’t share yet verdicts for three media items.",useful:["It was created by…","The source is…","It may be misleading because…","We should check…"],oge:{kind:"GRAMMAR TRANSFORM",task:"The photo ___ at the school event last Friday. (TAKE)",options:["took","was taken","is taking"],answer:1,tip:"Определите время, затем форму be, затем V3: was + taken."},writing:"Write a 60–80-word fact-check note with a verdict and evidence.",home:["Complete a passive process task.","Review source vocabulary.","Record a process explanation."]
  },
  {
    id:16,title:"THE CITY CHALLENGE",theme:"city · route · practical information",accent:"blue",objective:"Build a feasible route and adapt it to disruption.",grammar:"relative clauses · modals · comparisons",pronunciation:"connected directions",
    context:"A visiting teenager has four hours, £25 and three interests: street art, music and unusual food.",input:"The market, which closes at four, is cheaper than the riverside cafés. The music space is near the station, but visitors have to book. The street-art route is free and short enough to do on foot. A platform change may affect the final train.",words:[["neighbourhood","part of a town/city"],["admission","price or permission to enter"],["nearby","not far away"],["on foot","by walking"],["across from","on the opposite side"]],sortTitle:"ROUTE OR WARNING?",categories:["route","warning"],sort:[["turn left at the library","route"],["walk across the bridge","route"],["closes at four","warning"],["booking required","warning"]],notice:["the market, which closes at four","a route that is free","a place where teens perform"],rule:"Используйте relative clauses для точного описания места, modals — для правил/советов, comparisons и too/enough — для выбора маршрута.",mistake:"near from ✗ → near / close to ✓",type:[["The market is the place ___ we can eat cheaply.","where","Use where for a place."],["The route is short ___ to walk.","enough","Enough follows an adjective."]],speaking:"Ask for missing information, adapt the route and give clear directions.",useful:["How do we get to…?","It’s across from…","We have to…","It’s worth visiting because…"],oge:{kind:"ANNOUNCEMENT",task:"Which word most often introduces changed travel information?",options:["instead","beautiful","probably"],answer:0,tip:"В объявлениях особенно отслеживайте delayed, platform, instead, now — после них часто идёт изменение."},writing:"Write a 70–90-word four-hour itinerary with practical warnings.",home:["Retrieve direction phrases.","Write five clarification questions.","Create a route in your city."]
  },
  {
    id:17,title:"YOUR FUTURE, NOT A JOB TITLE",theme:"skills · future · possibility",accent:"pink",objective:"Explain strengths and possible future paths.",grammar:"might/may/could · future review · verb patterns",pronunciation:"word stress in skill families",
    context:"The group creates a future-skills feature instead of choosing one lifelong job.",input:"Maya might work with sound or science, but she does not have to choose now. Leo is thinking of learning user-interface design. Zara could use her communication skills in many fields. Noah is going to improve his editing this year because he enjoys telling visual stories.",words:[["strength","something you do well"],["flexible","able to change"],["work independently","work without constant help"],["solve problems","find answers to difficulties"],["be interested in","want to learn more about"]],sortTitle:"CLAIM OR EVIDENCE?",categories:["claim","evidence"],sort:[["I’m creative.","claim"],["I’m reliable.","claim"],["I edited three school videos.","evidence"],["I always meet project deadlines.","evidence"]],notice:["might work with sound","is thinking of learning","is going to improve"],rule:"might/may/could — возможность; be thinking of + -ing — развивающийся план; going to — более определённое намерение.",mistake:"I am interesting in design ✗ → I am interested in design ✓",type:[["I’m thinking of ___ (learn) design.","learning","Of is followed by -ing here."],["I ___ work with technology, but I’m not sure.","might","Use might for possibility."]],speaking:"Present three possible futures and one realistic next-step plan.",useful:["I’m good at…","I might…","I’m thinking of…","The evidence is…","My next step is…"],oge:{kind:"PERSONAL EMAIL",task:"A friend asks two questions about future plans. What must your reply do?",options:["answer one in detail","answer both and organise the message","write a universal memorised paragraph"],answer:1,tip:"Ответьте на все вопросы друга, разделите смысл на абзацы и проверьте формат."},writing:"Write a 90–110-word future-plan email fragment.",home:["Retrieve final vocabulary.","Plan the email.","Prepare personal evidence for Episode 18."]
  },
  {
    id:18,title:"FINAL MISSION: LEVEL UP LIVE",theme:"final checkpoint · integrated B1",accent:"yellow",objective:"Create and present a complete teen-media feature.",grammar:"integrated A2+–B1 choice",pronunciation:"thought groups · key stress · self-correction",
    context:"You are the fifth LEVEL UP LAB contributor. Choose one feature brief and take it from source material to a live two-minute presentation.",input:"Choose one: a better school idea; a smart digital habit challenge; an experience worth trying; a city mini-guide; or a future skill teens need. Use facts from the source, language from at least four episodes and your own clear recommendation.",words:[["brief","instructions for a project"],["relevant","connected to the purpose"],["evidence","facts supporting an idea"],["recommendation","advice about the best choice"],["reflect","think carefully about progress"]],sortTitle:"SOURCE OR YOUR IDEA?",categories:["source","idea"],sort:[["a stated price","source"],["an opening time","source"],["your recommendation","idea"],["your personal example","idea"]],notice:["Use the form that matches your meaning.","Connect each claim to evidence.","Do not force every grammar item into one answer."],rule:"Final mission: точность важна, но выбор языка должен служить смыслу. Планируйте opening → points → evidence/example → recommendation → closing.",mistake:"Сложнее не всегда лучше. Короткая точная фраза сильнее длинной конструкции с ошибкой.",type:[["If the plan ___ realistic, more students will join.","is","First conditional: Present Simple after if."],["The poster ___ (create) last week.","was created","Past passive: was + V3."]],speaking:"Prepare for 40 seconds, speak for two minutes, then answer three tutor questions.",useful:["My feature is about…","The evidence shows…","For example…","I’d recommend…","To sum up…"],oge:{kind:"FINAL INTEGRATED TASK",task:"What is the best use of 40 seconds of preparation?",options:["write a full script","note key words for every point","memorise one long introduction"],answer:1,tip:"Запишите ключевые слова по каждому пункту. Полный текст отнимает время и мешает говорить естественно."},writing:"Write a 100–120-word final feature, then revise it after tutor feedback.",home:["Revise the final product.","Record a second version.","Choose one precise B1 next step."]
  }
];
